development:
  adapter: postgresql
  encoding: unicode
  database: portfolio_dev
  pool: 2
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: db

test:
  adapter: postgresql
  encoding: unicode
  database: portfolio_test
  pool: 2
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: db
